name: Deploy to VPS

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Node VPS Deployment
      uses: Techie-Pi/node-vps-deployment@v1.1
      with:
        remote-path: "~/SatanBot"
        host: 216.128.131.152
        username: "anthonycastaneda"
        port: 22
        password: ${{ secrets.PASSWORD }}
        pm2-id: "SatanBot"
